### ISSUE TITLE
PE article

### ISSUE THREAD

**Issue by xkrt** [corkami/docs#1]
Where can I found on github copy of https://code.google.com/p/corkami/wiki/PE ?

**Comment by angea** [comment]
there is no formatted copy for now.
just a temporary backup
https://github.com/angea/wiki_old/blob/master/PE.wiki

**Comment by angea** [comment]
there is no formatted copy for now.
just a temporary backup until I port it
https://github.com/angea/wiki_old/blob/master/PE.wiki
